server.port=8080

# General settings
spring.application.name=emergency-dashboard

# GridDB Cloud Connection Properties
griddb.rest.url=https://<GRIDDB_CLOUD_HOST>/griddb/v2/<CLUSTER_NAME>/dbs/<DB_NAME>/containers/emergency_response_logs/rows
griddb.cloud.username=<YOUR_GRIDDB_USERNAME>
griddb.cloud.password=<YOUR_GRIDDB_PASSWORD>


# Expose Spring Boot Actuator Endpoints 
management.endpoints.web.exposure.include=*
